name: CI
on: push
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Build Package 
      run: yarn
    - name: Lint 
      run: yarn lint
    - name: Run tests
      run: yarn test:coverage
