name: npm-publish
on:
  push:
    branches:
      - master # Change this to your default branch
jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run build
      run: yarn build
    - name: Move package.json
      uses: sergeysova/jq-action@v2
      with:
        cmd: jq -c 'delpaths([["scripts"], ["devDependencies"]])' package.json >> ./dist/package.json
    - name: Copy README
      run: cp README.md ./dist/README.md
    - name: Publish if version has been updated
      id: publish
      uses: JS-DevTools/npm-publish@v1
      with:
        package: "./dist/package.json"
        token: ${{ secrets.NPM_AUTH_TOKEN }}
        check-version: true
    - if: steps.publish.outputs.type != 'none'
      run: |
        echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"

